### ISSUE TITLE
error 302

### ISSUE THREAD

**Issue by dezechristophe** [pierrecdn/phpipam#1]
container doesn"t work.
When I go http://<ip>[:<specific_port>]/
I got error 302 and ... nothing

10.72.253.3 - - [25/Sep/2015:06:43:40 +0000] "GET / HTTP/1.1" 302 634 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36"
10.72.253.3 - - [25/Sep/2015:06:43:40 +0000] "GET /?page=upgrade HTTP/1.1" 302 7110 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36"
10.72.253.3 - - [25/Sep/2015:06:43:40 +0000] "GET /?page=login HTTP/1.1" 302 7853 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36"

**Comment by pierrecdn** [comment]
There's nothing to do with the phpipam container itself (read the code of the Dockerfile), but with the [phpipam](http://github.com/phpipam/phpipam) project itself and the installation process. 

See https://github.com/phpipam/phpipam/issues/25 
Also, Remember that the packaged version is for now 1.16.003, which is a pre-release. 

To quickly solve your problem, navigate to http://<ip_or_vhost>/?page=install for the first access, it should work for the next tries.
