### ISSUE TITLE
uable to upload a file

### ISSUE THREAD

**Issue by gmoulard** [pierrecdn/phpipam#15]
Hi,

That so easy to user many thank !!!

When a use for export / import data whith file, I have a error message.  
Upload directory is not writable or do not exist.

do you have some solutions ? 

G.

**Comment by gmoulard** [comment]
hi,

I have find a solution
on my container, I have change the right on upload directory in /var/www/html/app/admin/import-export

root@12121212121:/var/www/html/app/admin/import-export# chmod 777 upload

and I remove the apache security file on the directory 

G.

**Comment by pierrecdn** [comment]
Fixed here: 1bec579
`chmod 777` is a bit violent :), here I just chown-ed the directory to let apache httpd write into it. 
Could you tell me if it fixes your issue ?

**Comment by pierrecdn** [comment]
Closing since I had no news, but I was able to test it and it worked.

**Comment by gmoulard** [comment]
I can't test it my work around is more large :(
