### ISSUE TITLE
Missing snmp support in php

### ISSUE THREAD

**Issue by gmoulard** [pierrecdn/phpipam#16]
Hi,

When a setup the snmp feature, I have this message : Missing snmp support in php

Do tou have some solution for me.

G.

**Comment by pierrecdn** [comment]
I maybe missed some package/deps to install, but the first issue is this one for now: https://github.com/phpipam/phpipam/issues/1406

i.e. I'll have to reference the projects referenced as submodules in the git repo.
Done here: eb4363a
Could you tell me if it fixes your issue by pulling the latest image ?

**Comment by isaqueprofeta** [comment]
@pierrecdn I sent you a pull request with the necessary changes for snmp support on #19

**Comment by pierrecdn** [comment]
Solved by @isaqueprofeta in #19

**Comment by gmoulard** [comment]
I will make a freech install I will test this update :)
