### ISSUE TITLE
unable to icmp scan.

### ISSUE THREAD

**Issue by pageb018** [pierrecdn/phpipam#22]
When trying to run any ping scan from the local agent, I get a JSON error. 

"Invalid JSON response - JSON_ERROR_SYNTAX"

**Comment by piteralt** [comment]
I too!

**Comment by pierrecdn** [comment]
Hi,
Thanks for the report.
Could you give me more context? 
* Which version of the container? Are you able to try with 1.3.1?
* Do you feel it's related to the container or to phpipam itself?

Thanks,

**Comment by pageb018** [comment]
So I am running 1.3.2 (updated via docker pull after initial install via Docker Compose yesterday. I am a bit of a novice when it comes to Docker, but to me it seems like a container issue. The reason I installed via docker is to move away from my full version running on a VM. I am running 1.3.2 on the full install as well and ICMP ping works just fine. 

I have attached a screen shot of the exact error. 
![screen shot 2018-07-06 at 8 43 21 am](https://user-images.githubusercontent.com/26354599/42379464-b86f88fa-80f8-11e8-9ab8-9d508291794e.png)

**Comment by pageb018** [comment]
I can try to set up another container instance using 1.3.1. I will report back.

**Comment by pageb018** [comment]
Confirmed it is an issue with 1.3.2.

The scan agent works correctly in 1.3.1.

**Comment by rubencode** [comment]
We are having the same issue... ping and fping are not present in the container...
Would it be possible to add ping/fping to the docker file?

**Comment by pierrecdn** [comment]
Hi,

This should be fixed by 8ef7c15, in which I add `iputils-ping`.
To keep the project in sync with phpipam version, I updated the tag so please `docker pull`.

Thanks for the reports, tell me if something is still not working.
