### ISSUE TITLE
anyway to change timezone?

### ISSUE THREAD

**Issue by pageb018** [pierrecdn/phpipam#23]
possible to set a TZ variable in the container? I noticed it is set to UTC, but would be nice to have ability to change this.  

Thanks again for the great container and quick support.

**Comment by pierrecdn** [comment]
Hi,

This is more a PR on phpipam side. Nothing  should depend on the server TZ and it's a bad practice to change it (how does it work if you're a global company with users in different places?).

When configuring a new user it should be possible to set his/her specific TZ.

Also nothing prevents you to override it by something more convenient for you by doing your own Dockerfile using a `FROM pierrecdn/phpipam`.
