### ISSUE TITLE
Crontab for discovery?

### ISSUE THREAD

**Issue by cchance27** [pierrecdn/phpipam#27]
Do you plan to include a discoveryCheck cron in the container?

**Comment by pierrecdn** [comment]
Hi,
Please could you elaborate? Is there something missing that you're used to work with on non-containerized phpipam setup?

**Comment by Swish24** [comment]
I believe he is speaking of, https://phpipam.net/news/automatic-host-availability-check/
Currently the container does not have automatic discovery. We would need to manually run the scan on each subnet, rather than having the ability to automatically run the search using cron.

**Comment by ix-mbadin** [comment]
@pierrecdn Add the following lines to your dockerfile:
`COPY pingCheck-cron /etc/cron.d/phpipam/
COPY discoveryCheck-cron /etc/cron.d/phpipam/`

Then create these two files:
**pingCheck-cron**
`SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin

# Run backup script
*/15 * * * * /usr/bin/php /var/www/phpipam/functions/scripts/pingCheck.php
`
**discoveryCheck-cron**
`SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin

# Run backup script
*/15 * * * * /usr/bin/php /var/www/phpipam/functions/scripts/discoveryCheck.php
`

**Comment by pierrecdn** [comment]
OK, now I understand better.
Unfortunately, running cron inside the same container isn't a good pattern (no more than 1 daemon in the container).
I would advise to schedule cron from the host, by creating a `/etc/cron.d/ipam` file: 
```
# update host statuses exery 15 minutes
*/15 * * * *  docker exec -ti ipam /usr/local/bin/php /var/www/html/functions/scripts/pingCheck.php
*/15 * * * *  docker exec -ti ipam /usr/local/bin/php /var/www/html/functions/scripts/discoveryCheck.php
```
Another approach would be for me to provide a dedicated phpipam-agent container (releasing https://github.com/phpipam/phpipam-agent), but it would imply an additional setup in phpipam (as for a non-Dockerized setup).

What do you think?

**Comment by pierrecdn** [comment]
So you have all options, since I finally created https://github.com/pierrecdn/phpipam-agent & `pierrecdn/phpipam-agent` Docker image to cover this need.

It seems more convenient and usable on orchestration platforms such as Docker compose, Mesos, Kubernetes and so on where you want to abstract every workload from the host.
