### ISSUE TITLE
Add multi-thread and LDAP support

### ISSUE THREAD

**Issue by mattpdmnz** [pierrecdn/phpipam#3]
Hi

Attached Docker file installs extensions necessary for LDAP support (allowing AD authentication) and for multi-thread so that subnet scanning is possible. Also fixes the config.php file so that it goes to the correct place with the correct name.

Additionally, have changed the php.ini file so that it sets timezone as UTC.

Thanks for your work 👍 

[Dockerfile.zip](https://github.com/pierrecdn/phpipam/files/509478/Dockerfile.zip)

**Comment by pierrecdn** [comment]
Hi,
Thanks for that (and sorry to react 8 months after :/).
You can probably take over https://github.com/pierrecdn/phpipam/pull/4 to make it mergeable (better to do a PR rather than sending files, more readable, reviews etc.)

**Comment by pierrecdn** [comment]
BTW, I just updated to 1.2

**Comment by pierrecdn** [comment]
This has been done in between. Thanks anyway for opening this issue.
