### ISSUE TITLE
Allow using Environment variable for DB Name

### ISSUE THREAD

**Issue by timwsuqld** [pierrecdn/phpipam#30]
Currently the MYSQL environment variables cover almost all the options, except for customising the DB name. 
```
$db['name'] = 'phpipam';
```
Can you please make it so we can customise that with environment variables as well.

Thanks

**Comment by pierrecdn** [comment]
Hi,
Yes true it was done like that because it was convenient to use with the db setup done via the auto-installer, using the defaults.
I can understand that for migration purposes and other use cases it could be nice...
Any PR to submit? ;)

**Comment by timwsuqld** [comment]
Merge request submitted. I can't see any reason it would cause issues for the auto-installer how I've done it, as it'll still default to phpipam when the environment variable isn't set.
