### ISSUE TITLE
Discovery Crons

### ISSUE THREAD

**Issue by christianreiss** [pierrecdn/phpipam#31]
Hey,

awesome, running was a breeze. How are the cron jobs (Alive Check/ Discovery Check) handled?
I might be mistaken, but I only seen apache processes in the container.

-Chris.

**Comment by infradump** [comment]
Duplicate of #27

**Comment by pierrecdn** [comment]
Thanks @infradump for answering.
TL;DR: use phpipam-agent.
@christianreiss I'm closing since it seems to me that it may answer your needs.
Feel free to reopen if not the case.
