### ISSUE TITLE
Request Timezone

### ISSUE THREAD

**Issue by jerebernard** [pierrecdn/phpipam#32]
Hello,

Is it possible to add inside the Docker File Timezone configuration as there is some logs it will be interesting.
`RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ /etc/timezone`

As there is some logs it will be interesting.

I am using docker compose so we could add inside into the docker compose a environnement variable : 
`ENV TZ=Europe/Paris`

Regards,

**Comment by pierrecdn** [comment]
Hi,
Why would it be an issue to have logs in UTC? It's generally a good practice to have UTC TZ at system level.
Wouldn't it be a PR for phpipam itself, in which you'd like each registered user to be able to set its TZ into phpipam?

**Comment by jerebernard** [comment]
Hello,
yes it's a PR for phpipam itself, with this config every phpipam admin can choose his own timezone.
It's easy to do it with a install directly on a OS but using a Docker install it's more complicated and I trying to don't create my own docker images but to use the one provided by the docker hub.
Regards,

**Comment by pierrecdn** [comment]
I meant, it could be for https://github.com/phpipam/phpipam project. You may open an issue there about users being able to set their own TZ.
As you may have seen there is no docker-compose file in this repo, so I don't see immediate need to introduce this (but I might be wrong).

**Comment by jerebernard** [comment]
Maybe I'm wrong but I though that you could add this into the DockerFile. So when the image is generated we could use this variable `ENV TZ` inside a docker-compose file.

**Comment by bcorner13** [comment]
Generally speaking, I concur that should leave servers in UTC. The reason being is who knows where you will spin this up.  It could just as easily be in western Europe or central Canada, or US east or west. 
In the old days when all of your computing was in the hall closet, people would use the local time zones.  but that is mostly in the past now.

**Comment by pierrecdn** [comment]
I'm not sure if there's still a debate on this, not seeing many people talking about it.
I'll close for now, feel free to reopen if you still think there is an issue related to this project.
