### ISSUE TITLE
About language 

### ISSUE THREAD

**Issue by trytrytogo** [pierrecdn/phpipam#35]
Thanks for pierrecdn. i want to change to chinese language. in "Hi, phpIPAM Admin",i select to chinese, and in "phpIPAM Server settings",i set default language to chinese, in "User management",i select Chinese,but ,it's no effect. always english.
some informations:
CentOS Linux release 7.5.1804 (Core)
Docker version 18.06.1-ce, build e68fc7a
pierrecdn/phpipam   latest
mysql               5.6
thanks.

**Comment by pierrecdn** [comment]
Hi @ixinshang,
Thanks for your report.
I guess this is related to missing locales in the container.

You probably can follow this tutorial to try adding your locale into the container: https://blog.mkowalski.net/2016/05/17/solving-locale-issues-with-docker-containers/

Please open a PR if you succeed, the idea being to add all those supported by default in phpipam and for which translations are (at least partially) done.

**Comment by trytrytogo** [comment]
> Hi @ixinshang,
> Thanks for your report.
> I guess this is related to missing locales in the container.
> 
> You probably can follow this tutorial to try adding your locale into the container: https://blog.mkowalski.net/2016/05/17/solving-locale-issues-with-docker-containers/
> 
> Please open a PR if you succeed, the idea being to add all those supported by default in phpipam and for which translations are (at least partially) done.

thanks,  i will change it and have a test, thansk.

**Comment by houstek** [comment]
same problem for me

Solved by editing the dockerfile : 
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y locales \
    && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && dpkg-reconfigure --frontend=noninteractive locales \
    && update-locale LANG=en_US.UTF-8
ENV LANG en_US.UTF-8 
ENV LC_ALL en_US.UTF-8

replace en_US.UTF-8 with your country

https://daten-und-bass.io/blog/fixing-missing-locale-setting-in-ubuntu-docker-image/

**Comment by trytrytogo** [comment]
thanks houstek @houstek ,it's OK.
thanks @pierrecdn
