### ISSUE TITLE
Setup Guide not connecting to DB

### ISSUE THREAD

**Issue by tylersiemers** [pierrecdn/phpipam#37]
Initial installation fails and doesn't create a database to get to login screen.

Unless I am missing something in the setup guide, I had to do the following to work around.

1. Change docker run for mysql to --name mysql not phpipam-mysql.
docker run --name mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -v /my_dir/phpipam:/var/lib/mysql -d mysql:5.6

2. Change ipam run for the link to mysql
docker run -ti -d -p 80:80 -e MYSQL_ENV_MYSQL_PASSWORD=my-secret-pw --name ipam --link mysql:mysql pierrecdn/phpipam

3. This allowed the initial installation to go right to the login in screen. I couldn't find the default password in the setup guide, so I went to:

localhost/?page=install

Recreated the DB, and assigned a new admin password. Is this right or did I miss something in the initial guide?

**Comment by pierrecdn** [comment]
Hi,

> This allowed the initial installation to go right to the login in screen

It is probably due to a previous installation or volume mount.

Theoretically you should arrive on an auto-installer page when you start containers for the first time, as explained using screenshots on the README.

**Comment by pierrecdn** [comment]
No feedbacks. I'm closing.
