### ISSUE TITLE
Please add gmaps_api_key variable to docker container for config.php/maps API usage

### ISSUE THREAD

**Issue by ayarbro** [pierrecdn/phpipam#40]
"Please configure config.php $gmaps_api_key to enable."
It would be great if a variable could be added to the container to alter the google maps API key from the container configuration.

**Comment by pierrecdn** [comment]
Hi,
True. Would you mind opening a PR for that? I'd be happy to merge it.

**Comment by pierrecdn** [comment]
Fixed by 0f337b9.

**Comment by ayarbro** [comment]
Thank you pierrecdn, sorry I didn't respond...life and work...

**Comment by pierrecdn** [comment]
NP, I understand that perfectly :)

**Comment by ayarbro** [comment]
Finally tested this (I'm sure by now everyone else and their mom has as well :) )  Works fantastic! Thanks again!
