### ISSUE TITLE
can not use SSL on LDAP

### ISSUE THREAD

**Issue by houstek** [pierrecdn/phpipam#41]
you can not use SSL on LDAP with this image.
For this to work, you must export the ROOT certificate in base 64 and paste it in /usr/local/share/ca-certificates then run the command: update-ca-certificates

Would it be possible to modify the image?

Thx

**Comment by pierrecdn** [comment]
Hi,
Most of LDAPS integrations suppose to introduce a custom CA, so I guess it will be done in most of the cases by extending this container and perform an `update-ca-certificates` as you mentioned.
How would you modify the image to support this in a generic way?

**Comment by houstek** [comment]
Hi,
Is it not possible to add the update-ca-certificates command to the DockerFile?

**Comment by pierrecdn** [comment]
It is, I just try to understand why would you do that in this container image?

(and not in yours, using something like
```
FROM pierrecdn/phpipam
COPY mycert.pem /usr/local/share/ca-certificates/mycert.pem
RUN update-ca-certificates
```

**Comment by houstek** [comment]
maybe I'm not familiar enough with Docker ;)

**Comment by okand** [comment]
This is probably bad advice but you can make it so that phpipam accepts self-signed certificates by mounting your own /etc/ldap/ldap.conf file into the container.

**Comment by pierrecdn** [comment]
:+1: for @okand suggestion.
In any case, this is specific to your setup, so I encourage you to adapt a bit, you have multiple solutions.
