### ISSUE TITLE
BASE Parameter in confg.php

### ISSUE THREAD

**Issue by xawen** [pierrecdn/phpipam#43]
Would it be possible to add an optional environment variable to configure the BASE directive to the config.php file?  https://phpipam.net/documents/prettified-links-with-mod_rewrite/

This would allow the container to stand behind a reverse proxy with a relative URL.

**Comment by pierrecdn** [comment]
Hi,

https://github.com/pierrecdn/phpipam/commit/888e2ce3f33384d41ed3b5a8d0b7facba8acf718 will probably fit your needs.
To test it please:
* pull `pierrecdn/phpipam:latest` to update your image.
* use `-e PHPIPAM_BASE=/your/proxied/path` in the run command.

Feel free to reopen if needed.
