### ISSUE TITLE
About "Bandwidth calculator"

### ISSUE THREAD

**Issue by trytrytogo** [pierrecdn/phpipam#45]
i have a Server(CentOS Linux release 7.5.1804 (Core),3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux),Docker version 18.09.0, build 4d60db4 and phpIPAM IP address management [v1.3.2]. it's works. i select "Bandwidth calculator",it's wrong.
Oops! Something went wrong!

Provided http error code is: 400: Bad Request.

i cant find logs.  any can help me. thanks.
https://i.bmp.ovh/imgs/2018/12/ac34273220b9e9ab.png

**Comment by pierrecdn** [comment]
Hi,
Unless proven wrong, this is not specific to the container.
You should open a bug on the phpipam/phpipam project.
Feel free to reopen if I'm wrong.
