### ISSUE TITLE
docker-compose instructions don't work

### ISSUE THREAD

**Issue by sbrueseke** [pierrecdn/phpipam#46]
docker compose instructions say:

  ipam:
    depends_on:
      - mysql
    image: pierrecdn/phpipam
    environment:
      - MYSQL_ENV_MYSQL_USER=root
      - MYSQL_ENV_MYSQL_PASSWORD=my-secret-pw
      - MYSQL_ENV_MYSQL_HOST=mysql

but in latest docker phpipam image config.php it is

$db['pass'] = getenv("MYSQL_ENV_MYSQL_ROOT_PASSWORD");

**Comment by bob05** [comment]
I was wondering my my DB connection broke suddenly...

I updated my docker-compose and it's now working:

environment:
      - MYSQL_ENV_MYSQL_PASSWORD=`<pw>`
      - MYSQL_ENV_MYSQL_USER=`<user>`
      - MYSQL_ENV_MYSQL_HOST=`mysql`
      - MYSQL_ENV_MYSQL_ROOT_PASSWORD=`<pw>`

**Comment by pierrecdn** [comment]
Thanks for reporting this!
In the previous commit I didn't take care about updating the documentation.
