### ISSUE TITLE
Docker instructions do not work

### ISSUE THREAD

**Issue by davdmrgn** [pierrecdn/phpipam#48]
Using the instructions to spin up a MySQL docker image, then linking the PHPIPAM docker image to it, the install URL is not accessible from `http://<ip>[:<specific_port>]/install/`. Forbidden: don't have permission. When browsing to the direct URL of the install.php file `http://<ip>[:<specific_port>]/install/index.php`, am presented with a Mod_rewrite error.

**Comment by davdmrgn** [comment]
Was able to get this to work on a different network in a different deployment. Chalking it up to network issues at that particular site.

**Comment by pierrecdn** [comment]
Hi,
Yes there is nothing specific here about apache httpd configuration, except what's actually done by the phpipam installer itself.
Good to know that it's OK.
