### ISSUE TITLE
Environment Variable Issue

### ISSUE THREAD

**Issue by angdigi** [pierrecdn/phpipam#49]
Hi - I specified the MySQL instance using the environment variable "MYSQL_ENV_MYSQL_HOST". However, it seems that the container does not use this because I receive the following error.

`Could not connect to database! SQLSTATE[HY000] [1045] Access denied for user 'phpipam_user'@'phpipam.br0.10' (using password: NO)`

The environment variable for the user is correct, though, but "phpipam.br0.10" should be the mysql container and not the phpipam container it's currently trying to connect to.

**Comment by pierrecdn** [comment]
Hi,
To me "phpipam.br0.10" is supposed to ne the mysql host you passed using the environement variable...
Depending on your network setup I cannot say if it should work or not.
What I am seeing here is that you have authentication/grant issues on mysql server side.

**Comment by angdigi** [comment]
Right, it's supposed to be. However, "phpipam.br0.10" is the phpipam host.

The environment variable I specified for the mysql host is "192.168.10.16"

**Comment by angdigi** [comment]
Perhaps my next question will help solve the first issue.

Where is the config.php file stored in this container? Is it possible to have a persistent path mapping?

**Comment by pierrecdn** [comment]
As you can see in the Dockerfile or by entering the container, the config.php is stored in `/var/www/html`.
If you want to override it, it's perfectly doable by mounting your own.

**Comment by pierrecdn** [comment]
I guess this is solved but feel free to reopen if not.

**Comment by angdigi** [comment]
We can keep this closed, but one quick question. Is it possible to use an existing mysql container, instead of dedicating one just for phpipam?

**Comment by pierrecdn** [comment]
Hi,
Sure it is. You should have a look at the configuration options, it's just a matter of passing the right container name, database name and credentials.

**Comment by angdigi** [comment]
When you say "container name" do you mean MYSQL_ENV_MYSQL_HOST? If so, can I specify IP address?
