### ISSUE TITLE
No website loads

### ISSUE THREAD

**Issue by djotaku** [pierrecdn/phpipam#5]
When I put in the address of the computer running the docker of PHPIPAM, nothing shows up in the browser. The output of Docker is:

192.168.1.6 - - [20/Apr/2017:07:31:07 +0000] "GET /?page=login HTTP/1.1" 302 786
4 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ch
rome/57.0.2987.133 Safari/537.36"   

But nothing shows up on screen with Firefox or Chrome.

**Comment by pierrecdn** [comment]
Hi,
I just upgraded to 1.2 to see.
Something was not clear in my documentation, you have to browse to /install.
Fixed now, check https://github.com/pierrecdn/phpipam/commit/ecf97ad6832e41051e6b0bd505761692d9c3c97a

**Comment by djotaku** [comment]
Thanks, dude. Works perfectly now.
