### ISSUE TITLE
no setuid bit on /bin/ping

### ISSUE THREAD

**Issue by jeanfabrice** [pierrecdn/phpipam#53]
```/bin/ping``` seems to lack the setuid bit:
```bash
 docker run -ti --rm  pierrecdn/phpipam:1.3.2 ls -l /bin/ping
-rwxr-xr-x 1 root root 61240 Nov 10  2016 /bin/ping
```
which results in ```ping: socket: Operation not permitted```when pinging using ```www-data``` user

Strangely enough, barely installing iputils-ping in php:7.2-apache image makes ```/bin/ping``` setuid-ed and I cannot quickly find something in your code that changes this behaviour.

Can you make ```/bin/ping``` setuid-ed ?

**Comment by pierrecdn** [comment]
Hi,
Any reproducer (in the UI), so that I can observe the case myself?
Thanks,

**Comment by jeanfabrice** [comment]
Hello, 

I simply ping scan a whole subnet with existing live hosts and instantly get the answer : 'No live host'.

After chmoding +s /bin/ping, hosts get discovered.

**Comment by jeanfabrice** [comment]
Well, it sounds like the error may be on my side.
I tried on another dockerhost (same docker version) and pinging seems to be ok. I will close this issue for now and comment back once I found the root cause of the issue.

**Comment by pierrecdn** [comment]
OK, let me know what were your findings.
