### ISSUE TITLE
Running in podman

### ISSUE THREAD

**Issue by codeman65** [pierrecdn/phpipam#54]
I am attempting to run this in a podman pod but the port is not being exposed.  Below is the commands I am using to setup the pod

podman run -dt --pod new:phpipam --name phpipam-mysql -p 8080:80 -e MYSQL_ROOT_PASSWORD=password -v /opt/phpipam:/var/lib/mysql -d docker.io/library/mysql:5.6

podman run -dt --pod phpipam -ti -d -e MYSQL_ENV_MYSQL_ROOT_PASSWORD=password docker.io/pierrecdn/phpipam:latest

When both containers are up and running in the pod I cannot access phpipam on port 8080

**Comment by pierrecdn** [comment]
Hi,
I'm not especially aware of the subtleties of podman. 
In docker, this is supposed to expose 8080 locally and install a SNAT rule from 8080 to 80 within the network namespace / veth interface of the container.
Anyway, I cannot help you on something which is not related to this project.
