### ISSUE TITLE
No way to edit PHP.INI

### ISSUE THREAD

**Issue by 1nerdyguy** [pierrecdn/phpipam#56]
Unless I'm missing it, which is quite possible, I don't see a way to edit he PHP.ini file for this to allow me to change things . From what I see, I need to edit it for the max_input_vars and bump it up to allow me to scan like a /22 with full hostnames.

**Comment by pierrecdn** [comment]
Hi,

I agree that this is based on base images and general purpose usage, consequently some realistic setups might require a bit of tuning.
2 ways to do it:
* add your own php.ini file by using volumes: `docker run -ti -d -v /my/php.ini:/usr/local/etc/php/php.ini pierrecdn/phpipam ..`
* fork & edit the php.ini file, but need local rebuild etc.

Should probably answer your concerns. Feel free to reopen if not.
