### ISSUE TITLE
discovery scans: Ping scan - don't work after first try

### ISSUE THREAD

**Issue by jdrye** [pierrecdn/phpipam#57]
I got a No alive host found! answer when i try to discovery scan :

![image](https://user-images.githubusercontent.com/25589001/69794432-88898000-11ca-11ea-953c-e5d1645b3106.png)

**Comment by pierrecdn** [comment]
Hi,
I would need more debug on your side, since I cannot guess what your environment is...
Please tcpdump, add trace points in the code, something that can make me think there is something related to this project.

**Comment by jdrye** [comment]
I hightly recommand to use officials phpipam images that are composed of 2 images, one for the webservice named phpipam-www and one named phpipam-cron that are used for auto-rescan device function. https://hub.docker.com/u/phpipam

For this closed issue, i think that the "no alive host found" return of scan result is "normal" when there is no new host in the newtork scanned.

Rgs,
