### ISSUE TITLE
Dockerfile build doesn't work due to enable-gd-native-ttf

### ISSUE THREAD

**Issue by davdmrgn** [pierrecdn/phpipam#59]
`enable-gd-native-ttf` is removed in PHP 7.2. Build fails.

https://github.com/pierrecdn/phpipam/blob/master/Dockerfile#L29

https://www.php.net/manual/en/migration72.other-changes.php

**Comment by pierrecdn** [comment]
Very true, thanks!
I'm wondering how it used to work in the first place with the 7.2 image.

Anyway, fixing it.
