### ISSUE TITLE
Can't build image for ARM

### ISSUE THREAD

**Issue by maximegy** [pierrecdn/phpipam#61]
Hello,
I have a probleme when i build image on raspberry.
I have this error:
```
configure: error: Cannot find ldap libraries in /usr/lib/x86_64-linux-gnu.
Removing intermediate container 98783f8dc2c0
The command '/bin/sh -c docker-php-ext-configure mysqli --with-mysqli=mysqlnd &&     docker-php-ext-install mysqli &&     docker-php-ext-configure gd --with-freetype-dir=/usr/include/freetype2 --with-png-dir=/usr/include --with-jpeg-dir=/usr/include &&     docker-php-ext-install gd &&     docker-php-ext-install curl &&     docker-php-ext-install json &&     docker-php-ext-install snmp &&     docker-php-ext-install sockets &&     docker-php-ext-install pdo_mysql &&     docker-php-ext-install gettext &&     ln -s /usr/include/x86_64-linux-gnu/gmp.h /usr/include/gmp.h &&     docker-php-ext-configure gmp --with-gmp=/usr/include/x86_64-linux-gnu &&     docker-php-ext-install gmp &&     docker-php-ext-install pcntl &&     docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu &&     docker-php-ext-install ldap &&     pecl install mcrypt-1.0.1 &&     docker-php-ext-enable mcrypt &&     echo ". /etc/environment" >> /etc/apache2/envvars &&     a2enmod rewrite' returned a non-zero code: 1
```
Can you help me with this problem or publish an image for ARM ?
Thanks a lot.

**Comment by pierrecdn** [comment]
Hi,
I guess it's related to the usage of `x86_64-linux-gnu` in multiple places in this line (include and dir libs for ex).
Could you try building using `$(gcc --dumpmachine)` instead of `x86_64-linux-gnu` and tell me if it fixes your issue?
Then I or you could do the PR eventually.

**Comment by amiga23** [comment]
"gcc -dumpmachine" returns "aarch64-unknown-linux-gnu". But replacing x86_64 with $(uname -m) works.

**Comment by evan766** [comment]
> Hi, I guess it's related to the usage of `x86_64-linux-gnu` in multiple places in this line (include and dir libs for ex). Could you try building using `$(gcc --dumpmachine)` instead of `x86_64-linux-gnu` and tell me if it fixes your issue? Then I or you could do the PR eventually.

thank you, it work for me
