### ISSUE TITLE
How to enable google 2FA with this image?

### ISSUE THREAD

**Issue by yurividal** [pierrecdn/phpipam#69]
Is it possible? "I get GoogleAuthenticator submodule missing." error

**Comment by pierrecdn** [comment]
This is due to the way phpipam is packaging the project.
They tend to use git submodules to distribute some parts of the software, so probably an improvement here would be to switch from fetching the tgz release to a `git --recurse-submodules` method instead.

**Comment by yurividal** [comment]
No problem mate. What i ended up doing was to mount the GoogleAuthenticator and qrcode submodule folders as persistent storages and add the code for each of these 2 inside the storages. Works for now.

**Comment by pierrecdn** [comment]
Hi, closing for now.
If you have any idea on how to integrate this within the build, I'm open to PRs! ;).
