### ISSUE TITLE
PLease update image to version 1.4.5

### ISSUE THREAD

**Issue by yurividal** [pierrecdn/phpipam#72]
1.4.5 was recebtly released with several crytical security fixes. Thanks!

**Comment by mhzawadi** [comment]
Hay,

I just updated my image to 1.4.5 - https://hub.docker.com/r/mhzawadi/phpipam

**Comment by pierrecdn** [comment]
Done as per https://github.com/pierrecdn/phpipam/commit/2e26d0608d8e1bc768af9a2577cc2b259759625e. Next time, feel free to open a PR instead, this change is pretty simple!
