### ISSUE TITLE
unable  set Prettify links to yes

### ISSUE THREAD

**Issue by zurekx** [pierrecdn/phpipam#8]
It is impossible to set Prettify links to yes. Probably problem is on apache rewrite. 
without Prettify links racks was not display (image of the racks) 
becouse the link to generate it is:
/app/tools/racks/draw_rack.php?rackId=2
I assume that the Prettify links must be turn on

**Comment by pierrecdn** [comment]
Hi,
this project is only for the Docker image.
You may be interested by this: https://github.com/phpipam/phpipam/issues/41
