### ISSUE TITLE
1.6 will not work behind reverse proxy

### ISSUE THREAD

**Issue by JordanSekky** [pierrecdn/phpipam#84]
The release of phpipam 1.6 [introduced a new config.php setting](https://github.com/phpipam/phpipam/releases/tag/v1.6.0) called `$trust_x_forwarded_headers`.

This setting is false by default, and breaks integration between this docker image and reverse proxies, as the X_FORWARDED_FOR_* headers are no longer trusted.

Please expose this option as an environment variable, or set it to `true` by default.

**Comment by pierrecdn** [comment]
Hi, would you mind submitting a PR for that?

**Comment by JordanSekky** [comment]
Submitted #85 !
