### ISSUE TITLE
Container Strategy for Parameters

### ISSUE THREAD

**Issue by jacksonp2008** [pierrecdn/phpipam#9]
This looks great, came right up with compose.  

What is the strategy for local parameters in config.php?  Do you have an environment variable to point to a local config.php?

**Comment by pierrecdn** [comment]
You would like for ex. to enter the Google Maps API key something like that ?
For now, I you may have see, this is absolutely not managed.

There are multiple possible approaches here:
* you can mount it as a volume (but you need to first extract the file, then append your parameters etc.)
* we could manage use-case by use-case with env-vars etc but it may be difficult to maintain in the long run (depends on phpipam project itself)

Feel free to precise your needs or to open a PR !
